spring.ai:
  chat:
    client.observations:
      include-prompt: true
      include-input: true
  ollama:
    base-url: http://localhost:11434
    chat:
      options:
        model: qwen2.5:latest
        temperature: 0.7
    init.pull-model-strategy: never
  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimensions: 1536
    batching-strategy: TOKEN_COUNT # Optional: Controls how documents are batched for embedding
    max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  mcp:
    client:
      enabled: true
      name: proposal-agent
      version: 1.0.0
      initialized: true
      request-timeout: 60000
      type: SYNC
      root-change-notification: true
      sse:
        connections:
          weather-server:
            url: http://localhost:8180
#
logging:
  level:
    org.springframework.ai: debug
    io:
      modelcontextprotocol:
        client: debug
        spec: debug
#
server:
  port: 8080  # 注意此处会覆盖spring.ai.mcp.server.port
  undertow:
    threads:
      io: 4       # I/O线程数 (建议设置为CPU核心数)
      worker: 40  # 工作线程数 (默认计算公式：CPU核心数 * 8)
    buffer-size: 1024  # 缓冲区大小(bytes)
    direct-buffers: true  # 使用直接内存
    http2: true
    max-parameters: 1000    # 最大请求参数数量
    max-headers: 200        # 最大header数量
    max-cookies: 200        # 最大cookie数量
    no-request-timeout: 60000  # 请求超时(ms)
    accesslog:
      dir: ./build/logs
      prefix: access_log
      suffix: log
      pattern: '%h %l %u %t "%r" %s %b'
#
spring.datasource:
    url: jdbc:h2:mem:proposal-agent.db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    username: sa
    password: password
    driverClassName: org.h2.Driver
#
spring.jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 10
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

#
spring.mvc:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600